on:
  push:
    paths-ignore:
      - README.md
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install tshark
        run: sudo apt-get install -y tshark

      - name: Install plugin
        run: mkdir -p ~/.local/lib/wireshark/plugins && cp antplus.lua ~/.local/lib/wireshark/plugins/

      - name: Run tests
        run: ./test.sh
